/*
CREATE TABLE TEST.PERSON (
  ID   NUMBER  GENERATED ALWAYS AS IDENTITY,
  NAME NVARCHAR2(100),
  AGE  NUMBER
);
*/

INSERT INTO PERSON (NAME, AGE) VALUES ('John' , 10);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bill' , 20);
INSERT INTO PERSON (NAME, AGE) VALUES ('Susan', 30);